name: Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test-e2e:
    name: Test Extension with Sunbeam
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Test with Sunbeam
        uses: sunbeam-labs/sbx_test_action@v1
        with:
          sunbeam-version: 'dev'
          extension-name: 'PennChopMicrobiomeProgram/sbx_WGS'
          extension-branch-name: ${{ github.head_ref }}
